#!/usr/bin/env python3
"""
Check Airfoil Matches Script
Finds all airfoils that exist in both the airfoil database and training_data_stec8.csv
"""

import os
import pandas as pd
from pathlib import Path

# Directory paths
SCRIPT_DIR = Path(__file__).parent.absolute()
AIRFOIL_DB_DIR = SCRIPT_DIR / "GenAirfoils" / "airfoil_database"
CSV_FILE = SCRIPT_DIR / "training_data_stec8.csv"

def get_airfoils_from_database():
    """Get all airfoil names from the database directory."""
    airfoils = []
    
    if not AIRFOIL_DB_DIR.exists():
        print(f"Error: Airfoil database directory not found at {AIRFOIL_DB_DIR}")
        return airfoils
    
    # Get all .dat files
    for file in AIRFOIL_DB_DIR.glob("*.dat"):
        # Remove .dat extension and any rotation suffixes
        name = file.stem
        # Skip rotated versions
        if "_rot" not in name:
            airfoils.append(name.lower())
    
    return sorted(set(airfoils))

def get_airfoils_from_csv():
    """Get unique airfoil names from the CSV file."""
    if not CSV_FILE.exists():
        print(f"Error: CSV file not found at {CSV_FILE}")
        return []
    
    try:
        df = pd.read_csv(CSV_FILE)
        # Get unique airfoil names and convert to lowercase for comparison
        airfoils = df['airfoil_name'].unique()
        return sorted([name.lower() for name in airfoils])
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return []

def find_matching_airfoils():
    """Find airfoils that exist in both database and CSV."""
    print("Checking for matching airfoils...")
    print("=" * 60)
    
    # Get airfoils from both sources
    db_airfoils = get_airfoils_from_database()
    csv_airfoils = get_airfoils_from_csv()
    
    print(f"Found {len(db_airfoils)} airfoils in database")
    print(f"Found {len(csv_airfoils)} unique airfoils in CSV")
    print("=" * 60)
    
    # Find matches (case-insensitive comparison)
    db_set = set(db_airfoils)
    csv_set = set(csv_airfoils)
    matches = sorted(db_set.intersection(csv_set))
    
    # Also find mismatches for information
    only_in_db = sorted(db_set - csv_set)
    only_in_csv = sorted(csv_set - db_set)
    
    return matches, only_in_db, only_in_csv

def display_results(matches, only_in_db, only_in_csv):
    """Display the results in a formatted way."""
    print(f"\nMATCHING AIRFOILS ({len(matches)} found):")
    print("=" * 60)
    
    if matches:
        for i, airfoil in enumerate(matches, 1):
            print(f"{i:3d}. {airfoil}")
    else:
        print("No matching airfoils found!")
    
    # Optionally show mismatches
    if only_in_db:
        print(f"\n\nAIRFOILS ONLY IN DATABASE ({len(only_in_db)}):")
        print("-" * 60)
        for airfoil in only_in_db[:10]:  # Show first 10
            print(f"  - {airfoil}")
        if len(only_in_db) > 10:
            print(f"  ... and {len(only_in_db) - 10} more")
    
    if only_in_csv:
        print(f"\n\nAIRFOILS ONLY IN CSV ({len(only_in_csv)}):")
        print("-" * 60)
        for airfoil in only_in_csv[:10]:  # Show first 10
            print(f"  - {airfoil}")
        if len(only_in_csv) > 10:
            print(f"  ... and {len(only_in_csv) - 10} more")

def save_matches_to_file(matches):
    """Save the matching airfoils to a text file."""
    output_file = SCRIPT_DIR / "matching_airfoils.txt"
    
    with open(output_file, 'w') as f:
        f.write("# Matching Airfoils\n")
        f.write("# These airfoils exist in both the database and CSV file\n")
        f.write("# Generated by check_airfoil_matches.py\n\n")
        
        # Write as a Python list for easy copy-paste
        f.write("MATCHING_AIRFOILS = [\n")
        for airfoil in matches:
            f.write(f'    "{airfoil}",\n')
        f.write("]\n\n")
        
        # Also write as a simple numbered list
        f.write("# Numbered list:\n")
        for i, airfoil in enumerate(matches, 1):
            f.write(f"# {i:3d}. {airfoil}\n")
    
    print(f"\n\nMatching airfoils saved to: {output_file}")

def main():
    """Main function."""
    print("Airfoil Matching Script")
    print("=" * 60)
    print(f"Database directory: {AIRFOIL_DB_DIR}")
    print(f"CSV file: {CSV_FILE}")
    print()
    
    # Find matches
    matches, only_in_db, only_in_csv = find_matching_airfoils()
    
    # Display results
    display_results(matches, only_in_db, only_in_csv)
    
    # Save matches to file
    if matches:
        save_matches_to_file(matches)
        
        # Print summary
        print("\n" + "=" * 60)
        print(f"SUMMARY: {len(matches)} matching airfoils found")
        print("=" * 60)
        
        # Generate Python list for easy copy-paste
        print("\nPython list for RANS automation script:")
        print("AIRFOILS_TO_PROCESS = [")
        for airfoil in matches:  # Show first 5 as example
            print(f'    "{airfoil}",')
        print("]")

if __name__ == "__main__":
    main()
